--- #YAML:1.0
name:                Parallel-Prefork
version:             0.08
abstract:            A simple prefork server framework
license:             ~
author:              
    - Kazuho Oku
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Class::Accessor::Fast:         0.31
    List::MoreUtils:               0
    Proc::Wait3:                   0.03
    Scope::Guard:                  0
    Time::HiRes:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
